"""Deterministic operator briefing.

The final human-facing text is templated from the verified evidence package
rather than generated by a fourth agent. That keeps every sentence traceable to
a tool result — an LLM cannot introduce a claim the checks do not support.
Whether an explanation agent would read better is left as a measurable
experiment, not assumed.
"""

from __future__ import annotations

from app.models.enums import ContingencyAction, VerificationStatus
from app.models.state import RunState
from app.models.verification import Recommendation

ACTION_HEADLINE = {
    ContingencyAction.CONTINUE: "Continue the mission to the delivery destination.",
    ContingencyAction.RETURN_TO_BASE: "Return to the launch base.",
    ContingencyAction.DIVERT_TO_SAFE_HUB: "Divert to the alternate recovery hub.",
    ContingencyAction.LAND_IMMEDIATELY: "Execute a forced landing.",
    ContingencyAction.ESCALATE: "Escalate to the remote Pilot in Command.",
}


def build_briefing(state: RunState, recommendation: Recommendation) -> str:
    lines: list[str] = []
    decision = state.contingency_decision

    if decision is not None:
        lines.append(f"CONTINGENCY: {decision.action} ({decision.severity})")
        lines.append(ACTION_HEADLINE.get(decision.action, ""))
        if decision.reason_codes:
            lines.append("Reasons: " + ", ".join(c.value for c in decision.reason_codes))
        lines.append("")

    if state.energy_estimate is not None:
        e = state.energy_estimate
        lines.append(
            f"Energy: {e.usable_energy_wh:.1f} Wh usable above a {e.reserve_energy_wh:.1f} Wh "
            f"reserve, {e.remaining_flight_time_sec:.0f} s endurance at {e.estimated_power_w:.0f} W."
        )
    if state.reachability is not None:
        lines.append(
            f"Reachability: {state.reachability.max_reachable_distance_m:.0f} m maximum "
            f"downwind radius; {len(state.reachability.reachable_candidate_ids)} preplanned "
            f"site(s) inside the envelope."
        )
    if state.energy_estimate or state.reachability:
        lines.append("")

    if recommendation.recommended_candidate_id:
        lines.append(
            f"RECOMMENDED SITE: {recommendation.recommended_candidate_name} "
            f"({recommendation.recommended_candidate_id})"
        )
        if recommendation.certification_status is not None:
            lines.append(
                f"Classification: {recommendation.candidate_tier} / "
                f"{recommendation.certification_status}"
            )
        if recommendation.recommended_route_id:
            lines.append(f"Route: {recommendation.recommended_route_id}")
        lines.append("")

    if recommendation.rejected_options:
        lines.append("REJECTED OPTIONS")
        for option in recommendation.rejected_options:
            codes = ", ".join(c.value for c in option.reason_codes) or "unspecified"
            lines.append(f"  {option.candidate_id} ({option.name}): {codes}")
            if option.detail:
                lines.append(f"    {option.detail}")
        lines.append("")

    lines.append(f"VERIFICATION: {recommendation.verification.verification_status}")
    for check in recommendation.verification.checks:
        mark = "PASS" if check.passed else ("FAIL" if check.passed is False else "N/A ")
        lines.append(f"  [{mark}] {check.name} — {check.detail}")
    lines.append("")

    if recommendation.verification.verification_status is VerificationStatus.PASS:
        lines.append("REMOTE OPERATOR APPROVAL REQUIRED before any action is taken.")
    else:
        failed = ", ".join(c.name for c in recommendation.verification.failed_checks())
        lines.append(f"NO VERIFIED PLAN. Failed checks: {failed or 'none recorded'}.")
        lines.append("Escalated to the remote Pilot in Command.")

    lines.append("SIMULATION ONLY — no flight command is sent by this system.")
    return "\n".join(line for line in lines if line is not None)
