"""Shared enumerations for the SafeDrop decision layer."""

from __future__ import annotations

from enum import StrEnum


class ContingencyAction(StrEnum):
    """The contingency action space (see overview.md §12)."""

    CONTINUE = "CONTINUE"
    RETURN_TO_BASE = "RETURN_TO_BASE"
    DIVERT_TO_SAFE_HUB = "DIVERT_TO_SAFE_HUB"
    LAND_IMMEDIATELY = "LAND_IMMEDIATELY"
    ESCALATE = "ESCALATE"


class FailureFamily(StrEnum):
    """Coverage taxonomy for the benchmark.

    A benchmark weighted entirely toward one family measures one thing well and
    everything else not at all. Every scenario declares its family so coverage
    can be reported rather than assumed.
    """

    ENERGY = "ENERGY"
    PROPULSION_AIRFRAME = "PROPULSION_AIRFRAME"
    NAVIGATION_CONTROL = "NAVIGATION_CONTROL"
    ENVIRONMENT = "ENVIRONMENT"
    CONNECTIVITY_TRAFFIC = "CONNECTIVITY_TRAFFIC"


class Severity(StrEnum):
    NOMINAL = "NOMINAL"
    ADVISORY = "ADVISORY"
    CAUTION = "CAUTION"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class SubsystemState(StrEnum):
    NOMINAL = "NOMINAL"
    DEGRADED = "DEGRADED"
    CRITICAL = "CRITICAL"
    UNKNOWN = "UNKNOWN"


class CandidateTier(StrEnum):
    """Landing candidate provenance tiers (coding instructions §20)."""

    PREPLANNED_SIMULATED_ELZ = "PREPLANNED_SIMULATED_ELZ"
    OFF_NOMINAL_LOWER_EXPOSURE = "OFF_NOMINAL_LOWER_EXPOSURE"
    OFF_NOMINAL_LAST_RESORT = "OFF_NOMINAL_LAST_RESORT"


class CertificationStatus(StrEnum):
    SIMULATED = "SIMULATED"
    NON_CERTIFIED = "NON_CERTIFIED"


class GroundStatus(StrEnum):
    VALID = "VALID"
    REJECTED = "REJECTED"
    UNVERIFIED = "UNVERIFIED"


class FreshnessStatus(StrEnum):
    CURRENT = "CURRENT"
    STALE = "STALE"
    UNKNOWN = "UNKNOWN"
    FIXED_SCENARIO = "FIXED_SCENARIO"


class VerificationStatus(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    NOT_RUN = "NOT_RUN"


class WorkflowState(StrEnum):
    """Deterministic orchestration state machine (agent_architecture.md §34)."""

    START = "START"
    STATE_PREPARED = "STATE_PREPARED"
    CONTINGENCY_CLASSIFIED = "CONTINGENCY_CLASSIFIED"
    REACHABILITY_READY = "REACHABILITY_READY"
    ELZ_CONTEXT_CHECKED = "ELZ_CONTEXT_CHECKED"
    ROUTE_VERIFIED = "ROUTE_VERIFIED"
    SAFETY_VERIFIED = "SAFETY_VERIFIED"
    OPERATOR_PENDING = "OPERATOR_PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    COMPLETE = "COMPLETE"
    ESCALATED = "ESCALATED"


class OperatorDecision(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"


class ReasonCode(StrEnum):
    """Machine-readable reason codes. Free text is never the safety contract."""

    # Contingency
    RAPID_SOC_LOSS = "RAPID_SOC_LOSS"
    LOW_STATE_OF_CHARGE = "LOW_STATE_OF_CHARGE"
    BATTERY_OVERHEAT = "BATTERY_OVERHEAT"
    MOTOR_DEGRADATION = "MOTOR_DEGRADATION"
    NAVIGATION_DEGRADED = "NAVIGATION_DEGRADED"
    LINK_DEGRADED = "LINK_DEGRADED"
    HIGH_WIND_RISK = "HIGH_WIND_RISK"
    PAYLOAD_INSTABILITY = "PAYLOAD_INSTABILITY"
    AIRFRAME_VIBRATION = "AIRFRAME_VIBRATION"
    PROPULSION_THERMAL = "PROPULSION_THERMAL"
    ABNORMAL_POWER_DRAW = "ABNORMAL_POWER_DRAW"
    GNSS_DEGRADED = "GNSS_DEGRADED"
    SENSOR_DISAGREEMENT = "SENSOR_DISAGREEMENT"
    GUST_EXCEEDANCE = "GUST_EXCEEDANCE"
    LOST_LINK = "LOST_LINK"
    DESTINATION_UNAVAILABLE = "DESTINATION_UNAVAILABLE"
    INSUFFICIENT_RTB_ENERGY = "INSUFFICIENT_RTB_ENERGY"
    INSUFFICIENT_MISSION_ENERGY = "INSUFFICIENT_MISSION_ENERGY"
    INSUFFICIENT_HUB_ENERGY = "INSUFFICIENT_HUB_ENERGY"
    MISSION_ENERGY_SUFFICIENT = "MISSION_ENERGY_SUFFICIENT"
    RTB_ENERGY_SUFFICIENT = "RTB_ENERGY_SUFFICIENT"
    HUB_ENERGY_SUFFICIENT = "HUB_ENERGY_SUFFICIENT"
    INSUFFICIENT_AIRCRAFT_STATE = "INSUFFICIENT_AIRCRAFT_STATE"

    # Ground
    PEOPLE_PRESENT = "PEOPLE_PRESENT"
    PEDESTRIAN_OCCUPANCY = "PEDESTRIAN_OCCUPANCY"
    VEHICLE_OCCUPANCY = "VEHICLE_OCCUPANCY"
    ANIMAL_EXPOSURE = "ANIMAL_EXPOSURE"
    CONSTRUCTION_OBSTRUCTION = "CONSTRUCTION_OBSTRUCTION"
    INSUFFICIENT_VISIBLE_CLEAR_AREA = "INSUFFICIENT_VISIBLE_CLEAR_AREA"
    INSUFFICIENT_AREA = "INSUFFICIENT_AREA"
    STANDING_WATER = "STANDING_WATER"
    OBSTACLE_CLEARANCE_INSUFFICIENT = "OBSTACLE_CLEARANCE_INSUFFICIENT"
    TEMPORARY_RESTRICTION_ACTIVE = "TEMPORARY_RESTRICTION_ACTIVE"
    GROUND_DATA_STALE = "GROUND_DATA_STALE"
    NO_CURRENT_VISUAL_CONFIRMATION = "NO_CURRENT_VISUAL_CONFIRMATION"
    UNCORROBORATED_LAST_RESORT_SITE = "UNCORROBORATED_LAST_RESORT_SITE"
    GROUND_CLEAR = "GROUND_CLEAR"

    # Candidate generation filters
    SCHOOL_PROXIMITY = "SCHOOL_PROXIMITY"
    HOSPITAL_PROXIMITY = "HOSPITAL_PROXIMITY"
    PLAYGROUND_PROXIMITY = "PLAYGROUND_PROXIMITY"
    ROAD_CONFLICT = "ROAD_CONFLICT"
    BUILDING_CONFLICT = "BUILDING_CONFLICT"
    RAILWAY_PROXIMITY = "RAILWAY_PROXIMITY"
    POWER_INFRASTRUCTURE_PROXIMITY = "POWER_INFRASTRUCTURE_PROXIMITY"

    # Route / airspace
    AIRSPACE_SEPARATION_VIOLATION = "AIRSPACE_SEPARATION_VIOLATION"
    RESTRICTED_AIRSPACE_INTERSECTION = "RESTRICTED_AIRSPACE_INTERSECTION"
    ROUTE_OBSTACLE_INTERSECTION = "ROUTE_OBSTACLE_INTERSECTION"
    INSUFFICIENT_ROUTE_ENERGY = "INSUFFICIENT_ROUTE_ENERGY"
    DESCENT_CORRIDOR_BLOCKED = "DESCENT_CORRIDOR_BLOCKED"
    AIRSPACE_DATA_STALE = "AIRSPACE_DATA_STALE"
    TRAFFIC_VERIFICATION_UNAVAILABLE = "TRAFFIC_VERIFICATION_UNAVAILABLE"
    ROUTE_VERIFIED = "ROUTE_VERIFIED"

    # Terminal / abstention
    NO_REACHABLE_PREMAPPED_ELZ = "NO_REACHABLE_PREMAPPED_ELZ"
    NO_GROUND_SAFE_ELZ = "NO_GROUND_SAFE_ELZ"
    NO_VERIFIED_ROUTE = "NO_VERIFIED_ROUTE"
    NO_CANDIDATE_GENERATED = "NO_CANDIDATE_GENERATED"
    AGENT_FAILURE = "AGENT_FAILURE"
